### PR TITLE
add DTM and DTG data from Konstantopoulou et. al (2023)

### PR DESCRIPTION
**Pull request by james-trayford**
add data from Konstantopoulou et. al (2023)

### CODE REVIEW

**Comment by EvgeniiChaikin** [comment]
I don't think this PR was ready. The data should have been included as a `MultiRedshiftObservationalData` object, so that the data at all redshifts is contained in a single file.

See e.g. https://github.com/SWIFTSIM/velociraptor-comparison-data/blob/master/data/GalaxyStellarMassFunction/conversion/convertBehroozi2019.py

I will submit an MR to fix it.

**Comment by MatthieuSchaller** [comment]
You are right. That's a better option. My bad.

**Comment by james-trayford** [comment]
> I don't think this PR was ready. The data should have been included as a `MultiRedshiftObservationalData` object, so that the data at all redshifts is contained in a single file.
> 
> See e.g. https://github.com/SWIFTSIM/velociraptor-comparison-data/blob/master/data/GalaxyStellarMassFunction/conversion/convertBehroozi2019.py
> 
> I will submit an MR to fix it.

OK, thanks for checking - is that the universal way of treating  multi redshift data sets now? I notice there are still some other zNNNpNNN files referenced in the autoplotter scripts

**Comment by james-trayford** [comment]
@EvgeniiChaikin also happy to try implementing it correctly following the Behroozi example - let me know what you want to do

**Comment by EvgeniiChaikin** [comment]
@james-trayford, thanks! 

I have created a pull request here #185 Could you please take a look and confirm whether everything looks good? Note that I have also converted the data from Peroux (2020) into multi-z format.

Also regarding the current (merged) PR, is it correct that no cosmology, metallicity, and mass function corrections are needed?

**Comment by james-trayford** [comment]
Thanks @EvgeniiChaikin, I also had added DTG data, so epanded your corrections to that script to - see https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/186

if we merge that branch into this one (`multi-z-scripts`) I think this is then ready to merge into `main`

**Comment by james-trayford** [comment]
...and then merge https://github.com/SWIFTSIM/pipeline-configs/pull/267 for the `pipeline-configs`

**Comment by james-trayford** [comment]
@EvgeniiChaikin 

> Also regarding the current (merged) PR, is it correct that no cosmology, metallicity, and mass function corrections are needed?

These are unitless - no cosmology corrections and no obvious IMF corrections. These metallicities are definedrelative to the sun so don't think Z corrections applicable

**Pull request merged**
