### PR TITLE
Change the BlackHoleMassSpecificStarFormationRate script to write one…

### PR DESCRIPTION
**Pull request by MatthieuSchaller**
… file with the data without upper limits and one with upper limits

### CODE REVIEW

**Review by EvgeniiChaikin — CHANGES_REQUESTED** [review]
I see that ~50 per cent of code lines in this file are unnecessary (i.e. a lot of duplicate code). We definitely need to correct it.

@MatthieuSchaller is it okay if I submit a commit to this branch to shorten the file? (I assume that you may be busy with many other tasks, so I can do this one myself).

**Comment by MatthieuSchaller** [comment]
Yes, sure, go ahead.

**Review by EvgeniiChaikin — APPROVED** [review]

**Comment by EvgeniiChaikin** [comment]
@MatthieuSchaller the script should now be ready.

ssfr_rate_black_hole_mass_50

**Comment by EvgeniiChaikin** [comment]
Thanks @MatthieuSchaller, I have just pushed the new version

ssfr_rate_black_hole_mass_50

**Comment by MatthieuSchaller** [comment]
Thanks! Looks great like this.

**Pull request merged**
