### PR TITLE
Add Behroozi2019 passive fractions

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
- Galaxy passive fractions versus stellar mass at redshifts from z=0 to z=5, all from `Behroozi2019`

<h2>Full set of curves</h2>

Passive_fractions_all_z
Passive_fractions_all_z_centrals

<h2>Examples</h2>

_z=0_:

stellar_mass_passive_fraction_100
stellar_mass_passive_fraction_centrals_100

_z=1_:

stellar_mass_passive_fraction_100_z1
stellar_mass_passive_fraction_centrals_100_z1

### CODE REVIEW

**Comment by JBorrow** [comment]
Looks like the error bars at z=0 are broken - at ~1e11 they don't intersect the median line at all.

**Comment by JBorrow** [comment]
Any update on the error bars here?

**Comment by EvgeniiChaikin** [comment]
That seems to be just an unlucky case... (I know it is a bad excuse)

There are 24 new observational-data files in this PR - the passive fractions of all objects and centrals at 12 different redshifts.

One out of these 24 obs data files - the raw observational data file from Behroozi for all objects at z=0 - happens to have negative lower error bars (**Err-**)!

You can have a look at this file yourself [`Behroozi2019_qf_a1.002310.dat`] (the relevant columns are 0, 4, 5, and 6) 

```
#Observed stellar masses in Msun
#Bestfit_Galaxy_Counts is the number of galaxies in the bin for the bestfit model.
#Log10(SM_Center) FQ(SSFR<PRIMUS_Thresh) Err+ Err- FQ(SSFR<1e-11) Err+ Err- FQ_UVJ Err+ Err- SM_Left_Edge SM_Right_Edge Bestfit_Galaxy_Counts
7.3 0.521813 0.0998474 0.214907 0.0175615 0.0204834 0.0153427 0.0476966 0.0319035 0.040392 7.2 7.4 697949
7.5 0.478641 0.0986016 0.193113 0.0222204 0.0207845 0.018769 0.0738591 0.0377276 0.0602618 7.4 7.6 623750
7.7 0.438578 0.0920173 0.172465 0.0281734 0.0205035 0.0228442 0.111375 0.0324417 0.0857268 7.6 7.8 534973
7.9 0.395564 0.0872626 0.148796 0.0357291 0.0236383 0.0267465 0.154485 0.0340668 0.108797 7.8 8 443896
8.1 0.353756 0.0709984 0.1286 0.0477594 0.0273616 0.0323228 0.198506 0.0370163 0.119032 8 8.2 361081
8.3 0.317025 0.0596164 0.098853 0.0642986 0.035911 0.0367375 0.235763 0.0324949 0.117178 8.2 8.4 293179
8.5 0.288053 0.0573274 0.0829152 0.0855257 0.0402458 0.0421991 0.253461 0.030685 0.102562 8.4 8.6 244710
8.7 0.2698 0.059363 0.0622603 0.104899 0.0396556 0.0441052 0.260628 0.0322751 0.08361 8.6 8.8 202575
8.9 0.262657 0.0519766 0.0505518 0.125433 0.0373869 0.0459298 0.263606 0.0332286 0.0788985 8.8 9 163545
9.1 0.266171 0.0450089 0.0436206 0.150215 0.0387995 0.0473699 0.269903 0.0282773 0.0733709 9 9.2 131212
9.3 0.278556 0.0410651 0.0363799 0.177714 0.0383692 0.0443538 0.288521 0.0292754 0.0683475 9.2 9.4 106542
9.5 0.3 0.0376553 0.0279594 0.210723 0.0333605 0.0424964 0.315765 0.0309976 0.0596595 9.4 9.6 87831
9.7 0.326769 0.0394465 0.018926 0.24586 0.0313867 0.0339639 0.346156 0.0345204 0.0466183 9.6 9.8 75055
9.9 0.359007 0.040454 0.00905937 0.287538 0.0259108 0.0251291 0.380753 0.0432442 0.035585 9.8 10 64082
10.1 0.402008 0.038966 0.000336438 0.338054 0.0260036 0.0132446 0.422648 0.0475059 0.0194011 10 10.2 57059
10.3 0.453842 0.0421768 -0.00583005 0.397518 0.0373576 0.00341609 0.469558 0.0541431 0.00721228 10.2 10.4 50287
10.5 0.512963 0.0535532 -0.00641894 0.471622 0.0518608 0.00310972 0.517634 0.0639139 -0.00302958 10.4 10.6 43908
10.7 0.577357 0.0743901 -0.005575 0.543473 0.0783647 -0.00365859 0.566477 0.0703916 -0.00417 10.6 10.8 34861
10.9 0.645644 0.0989059 -0.00540096 0.630398 0.0979007 -0.00253296 0.61433 0.0856108 -0.00110072 10.8 11 23574
11.1 0.724616 0.101785 0.000565529 0.72131 0.104591 -0.000945985 0.665151 0.0818554 0.00773227 11 11.2 12548
11.3 0.78491 0.0956526 0.00063622 0.805267 0.0903434 0.00594157 0.701562 0.0648629 0.00961637 11.2 11.4 5392
11.5 0.836473 0.0706266 -0.00311321 0.875446 0.0619754 -0.00236011 0.734901 0.0396492 0.0114982 11.4 11.6 2240
11.7 0.837583 0.0683082 -0.0165405 0.914804 0.049051 -0.00838834 0.75606 0.0248308 0.0186075 11.6 11.8 716
11.9 0.821224 0.0664148 -0.0104891 0.935323 0.0427468 -0.00585312 0.770935 0.0198677 0.0305762 11.8 12 201
12.1 0.772728 0.0642322 0.0162272 0.952381 0.047619 0.00501251 0.780233 0.0154467 0.0358612 12 12.2 42
```
**That is how the errors should be interpreted**
```
The column Err+ gives the difference between the 84th percentile model and the best-fit model; the column Err- gives the difference between the best-fit model and the 16th percentile model. Hence, if the best-fit value, Err+ , and Err- columns are A,
B, and C, respectively, the 68% confidence interval ranges from A-C to A+B.
```

These negative numbers cannot be `log10` of the errors, because 10 to the power of such close-to-zero numbers (e.g.  `-0.00585312`) is basically one. The latter is definitely not suited for the plot, because this would mean that the error bar is larger than the whole range along the y axis.

**Comment by JBorrow** [comment]
So the 16th percentile model is above the 50th percentile model? I see that the value is negative (that seems very odd to me)... Can you confirm this with Behroozi? This seems _very_ odd.

**Comment by EvgeniiChaikin** [comment]
Alright, I will send him an email.

**Comment by EvgeniiChaikin** [comment]
Should be all good now 

I did some basic tests, again - everything looks as expected

Screenshot from 2021-02-09 17-45-35

**Pull request merged**
