### PR TITLE
add SFH from Behroozi 2019 

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
**add SFH from Behroozi 2019** 

**Paper:** https://arxiv.org/pdf/1806.07893.pdf

**Data:** (from the paper above, left plot)

Screenshot from 2021-08-30 14-15-05

### CODE REVIEW

**Comment by JBorrow** [comment]
All data (including SFH data) should now come with a conversion script. I think the inclusion of data without conversion scripts (and hence significant missing metadata) is a mistake that we don't want to repeat.

**Comment by EvgeniiChaikin** [comment]
Yes, of course! But currently, the star formation history plot is an exception to this rule. See this: https://github.com/SWIFTSIM/pipeline-configs/blob/master/colibre/scripts/load_sfh_data.py

I agree that ideally, we need to properly (re-)write conversion scripts for each data sets that are present in that plot.

**Comment by JBorrow** [comment]
Yes, I'm aware that we have lots of data that doesn't come along with the metadata for SFH, but when we add new data there's no reason to not 'do it properly', even if the legacy data is still wrong.

**Comment by JBorrow** [comment]
I will let @bwvdnbro take it from here. Thanks Evgenii for your fast turnaround!

**Comment by JBorrow** [comment]
There are minor differences between black versions. Can you try updating the one you're using to the latest release?

**Comment by EvgeniiChaikin** [comment]
Thanks @JBorrow 

Yes, indeed, doing

`python3.8 -m pip install black --upgrade`

solved the problem

**Comment by JBorrow** [comment]
Ok, thanks! I'll let somebody else make the final merge decision as I've been away for a while and I'm not sure if anythings changed but I'm happy with this as-is

**Review by MatthieuSchaller — APPROVED** [review]

**Pull request merged**
