### PR TITLE
Add Behroozi2019 Galaxy Stellar Mass Function

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
Add Behroozi2019 Galaxy Stellar Mass Function at multiple redshifts

- All objects
- Passive objects

### CODE REVIEW

**Comment by EvgeniiChaikin** [comment]
<h2>EXAMPLES</h2>

http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/HAWK/L006N188/z0.0_01_REFERENCE/
http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/HAWK/L006N188/z2.0_01_REFERENCE/
http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/HAWK/L006N188/z3.7_01_REFERENCE/

**Comment by JBorrow** [comment]
Is this a fit or actual data points?

**Comment by JBorrow** [comment]
Also is active = total - passive?

**Comment by EvgeniiChaikin** [comment]
> Is this a fit or actual data points?

**Fit**. I indicated that in the `name` attribute of the produced files.

**Comment by EvgeniiChaikin** [comment]
> Also is active = total - passive?

Yeah, I guess so; but then I am not sure what to the with the errors.

Behroozi only provides GSMF for _all_ galaxies (including errors) and _passive_ galaxies (including errors)

**Pull request merged**
