### PR TITLE
Added GSMF data from Leja+ (2020).

### PR DESCRIPTION
**Pull request by jemme07**
Added GSMF data from Leja+ (2020). Uses panchromatic SED models that infer systematically higher masses and lower star formation rates than standard approaches.

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
Does it require any h-correction or are they doing things in h-free coordinates? 

Can we specify the IMF choice in the description?

**Comment by jemme07** [comment]
Everything is in h-free coordinates.

**Comment by MatthieuSchaller** [comment]
But did they assume the same h as us when constructing their results?

**Comment by jemme07** [comment]
Just added the IMF info. 

Right, regarding conversion , they used WMAP9 and give everything in h-free. So, if we would like to change cosmology, we would need to convert to h-units and back to h-free using the appropriate h-factors. This should be a very a small effect as the h values are now all very close to 0.7. I can include the conversions if you think is necessary.

**Comment by MatthieuSchaller** [comment]
We have typically done that for the other datasets. Factots of h^3 (as you'd expect on the y-axis) lead to a 10% difference between h=0.7 and EAGLE h.

**Comment by jemme07** [comment]
No worries, I'll do that.

**Comment by jemme07** [comment]
Done! Added the cosmology correction factors.

**Comment by MatthieuSchaller** [comment]
Thanks.

Sorry to be a pain, are we sure the masses are Msun/h and not Msun/h^2? That can be the case in SED fitting models.

**Comment by jemme07** [comment]
I did h^2, that should be the masses inferred from from luminosities.

**Review by MatthieuSchaller — APPROVED** [review]

**Pull request merged**
