### PR TITLE
Fixed errorbars and redshift error

### PR DESCRIPTION
**Pull request by JBorrow**
Fixes the errorbar and redshift error in the Muzzin 2013 data.

### CODE REVIEW

**Comment by JBorrow** [comment]
stellar_mass_evolution
With the fixed data

**Comment by MatthieuSchaller** [comment]
I see what I did wrong here.

The thing here is that assigning a single z here makes little sense.

**Comment by JBorrow** [comment]
Indeed - but I don't think it's so bad as long as we know that the value in the legend is the mean redshift of the observations.

**Comment by MatthieuSchaller** [comment]
Good for me

**Comment by JBorrow** [comment]
Let's wait on the CI to see if I messed anything up and then I'll merge.

**Pull request merged**
