### PR TITLE
SNIa data update

### PR DESCRIPTION
**Pull request by Fonotec**
This includes 14 more observations for the cosmic SNIa rate and one observation for the specific SFR vs the specific SNIa rate.

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
What about the SNIa rate files? Shouldn't these also be converted?

**Comment by Fonotec** [comment]
Yes, this includes the conversion files

**Comment by Fonotec** [comment]
Btw it would be good if you merge this because then it can be included in the pipeline, but as long as you don't merge this I will add more SNIa data if I find more datasets.

**Review by MatthieuSchaller — APPROVED** [review]
Looks good to me.

**Pull request merged**
